title: Candicetan # your name (or website title) here
logo: "/images/SC.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Credit analyst with extensive experience in risk analysis and recommending for various lending proposals. 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
